Added npm install support

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -46,6 +46,35 @@ if [ -z "$DART_SDK_URL" ]; then
     exit 1
 fi
 
+# NPM stuff
+cat_npm_debug_log() {
+  test -f $BUILD_DIR/npm-debug.log && cat $BUILD_DIR/npm-debug.log
+}
+
+# Output npm debug info on error
+trap cat_npm_debug_log ERR
+
+# Resolve node version using semver.io
+node_version="6.3.1"
+
+# Download node from Heroku's S3 mirror of nodejs.org/dist
+echo "-----> Downloading and installing node ${node_version} ..."
+node_url="http://s3pository.heroku.com/node/v$node_version/node-v$node_version-linux-x64.tar.gz"
+curl $node_url -s -o - | tar xzf - -C $BUILD_DIR
+
+# Move node (and npm) into ./vendor and make them executable
+mkdir -p $BUILD_DIR/vendor
+mv $BUILD_DIR/node-v$node_version-linux-x64 $BUILD_DIR/vendor/node
+chmod +x $BUILD_DIR/vendor/node/bin/*
+PATH=$PATH:$BUILD_DIR/vendor/node/bin
+
+# Clean any npm cache hanging about
+npm update -g
+npm cache clean
+npm install
+
+# NPM stuff end
+
 cd $BUILD_DIR
 
 message "-----> Installing Dart VM via URL $DART_SDK_URL"
